"""Init schema - all tables

Revision ID: 65d8a054421b
Revises: 
Create Date: 2026-04-28 22:12:34.862369

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '65d8a054421b'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('construction_costs_amenities',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('location', sa.String(), nullable=True),
    sa.Column('amenity_name', sa.String(), nullable=True),
    sa.Column('price_tier_1', sa.Numeric(), nullable=True),
    sa.Column('price_tier_2', sa.Numeric(), nullable=True),
    sa.Column('price_tier_3', sa.Numeric(), nullable=True),
    sa.Column('notes', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    schema='markets'
    )
    op.create_table('construction_costs_remodeling',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('location', sa.String(), nullable=True),
    sa.Column('rehab_item', sa.String(), nullable=True),
    sa.Column('metric', sa.String(), nullable=True),
    sa.Column('price_tier_1', sa.Numeric(), nullable=True),
    sa.Column('price_tier_2', sa.Numeric(), nullable=True),
    sa.Column('price_tier_3', sa.Numeric(), nullable=True),
    sa.Column('notes', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    schema='markets'
    )
    op.create_table('market_keys_master',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('market_slug', sa.String(), nullable=True),
    sa.Column('market_name', sa.String(), nullable=True),
    sa.Column('market_name_current', sa.String(), nullable=True),
    sa.Column('market_status', sa.String(), nullable=True),
    sa.Column('analyst_owner', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    schema='markets'
    )
    op.create_table('opex_by_bedrooms',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('market', sa.Integer(), nullable=True),
    sa.Column('bedrooms', sa.Integer(), nullable=True),
    sa.Column('pool_hot_tub_low', sa.Numeric(), nullable=True),
    sa.Column('pool_hot_tub_high', sa.Numeric(), nullable=True),
    sa.Column('outdoor_landscaping', sa.Numeric(), nullable=True),
    sa.Column('software', sa.Numeric(), nullable=True),
    sa.Column('insurance_hoi', sa.Numeric(), nullable=True),
    sa.Column('supplies', sa.Numeric(), nullable=True),
    sa.Column('capex_reserve', sa.Numeric(), nullable=True),
    sa.Column('cleaning_fee', sa.Numeric(), nullable=True),
    sa.Column('num_of_turns', sa.Integer(), nullable=True),
    sa.Column('property_taxes', sa.Numeric(), nullable=True),
    sa.Column('land_value', sa.Numeric(), nullable=True),
    sa.Column('appreciation', sa.Numeric(), nullable=True),
    sa.Column('hoa_fees', sa.Numeric(), nullable=True),
    sa.Column('furnishings_low', sa.Numeric(), nullable=True),
    sa.Column('furnishings_high', sa.Numeric(), nullable=True),
    sa.Column('consolidated_shipping', sa.Numeric(), nullable=True),
    sa.ForeignKeyConstraint(['market'], ['markets.market_keys_master.id'], ),
    sa.PrimaryKeyConstraint('id'),
    schema='markets'
    )
    op.create_table('opex_by_size',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('market', sa.Integer(), nullable=True),
    sa.Column('sqft', sa.Integer(), nullable=True),
    sa.Column('internet', sa.Numeric(), nullable=True),
    sa.Column('pest_control', sa.Numeric(), nullable=True),
    sa.Column('utilities', sa.Numeric(), nullable=True),
    sa.ForeignKeyConstraint(['market'], ['markets.market_keys_master.id'], ),
    sa.PrimaryKeyConstraint('id'),
    schema='markets'
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('opex_by_size', schema='markets')
    op.drop_table('opex_by_bedrooms', schema='markets')
    op.drop_table('market_keys_master', schema='markets')
    op.drop_table('construction_costs_remodeling', schema='markets')
    op.drop_table('construction_costs_amenities', schema='markets')
    # ### end Alembic commands ###
