"""add_underwriting_tables

Revision ID: e333243d95a7
Revises: b2673e068337
Create Date: 2026-05-18 01:13:32.568289

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'e333243d95a7'
down_revision: Union[str, Sequence[str], None] = 'b2673e068337'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('underwritings',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('market_id', sa.Integer(), nullable=True),
    sa.Column('analyst_id', sa.Integer(), nullable=True),
    sa.Column('approver_id', sa.Integer(), nullable=True),
    sa.Column('deal_status', sa.String(length=50), nullable=True),
    sa.Column('date_added', sa.Date(), nullable=True),
    sa.Column('approved_time', sa.DateTime(timezone=True), nullable=True),
    sa.Column('property_pending', sa.Boolean(), nullable=True),
    sa.Column('property_address', sa.String(length=255), nullable=True),
    sa.Column('city', sa.String(length=100), nullable=True),
    sa.Column('state', sa.String(length=2), nullable=True),
    sa.Column('days_on_market', sa.Integer(), nullable=True),
    sa.Column('sleep_capacity', sa.Integer(), nullable=True),
    sa.Column('purchase_price', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('cash_needed', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('all_in_cost', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('prr', sa.Numeric(precision=6, scale=4), nullable=True),
    sa.Column('budget_to_pp', sa.Numeric(precision=6, scale=4), nullable=True),
    sa.Column('low_gross_revenue', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('mid_gross_revenue', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('high_gross_revenue', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('l_cash_on_cash', sa.Numeric(precision=6, scale=4), nullable=True),
    sa.Column('m_cash_on_cash', sa.Numeric(precision=6, scale=4), nullable=True),
    sa.Column('h_cash_on_cash', sa.Numeric(precision=6, scale=4), nullable=True),
    sa.Column('turnkey', sa.Boolean(), nullable=True),
    sa.Column('furnished', sa.Boolean(), nullable=True),
    sa.Column('luxury', sa.Boolean(), nullable=True),
    sa.Column('wow_factor', sa.Boolean(), nullable=True),
    sa.Column('tax_efficient', sa.Boolean(), nullable=True),
    sa.Column('new_build', sa.Boolean(), nullable=True),
    sa.Column('new_construction', sa.Boolean(), nullable=True),
    sa.Column('existing_airbnb', sa.Boolean(), nullable=True),
    sa.Column('existing_airbnb_sold_furnished', sa.Boolean(), nullable=True),
    sa.Column('arv', sa.Boolean(), nullable=True),
    sa.Column('high_cash_on_cash', sa.Boolean(), nullable=True),
    sa.Column('low_cash_on_cash', sa.Boolean(), nullable=True),
    sa.Column('add_inground_pool', sa.Boolean(), nullable=True),
    sa.Column('renovation_level', sa.Boolean(), nullable=True),
    sa.Column('complex_deal', sa.Boolean(), nullable=True),
    sa.Column('funky', sa.Boolean(), nullable=True),
    sa.Column('remote', sa.Boolean(), nullable=True),
    sa.Column('secluded', sa.Boolean(), nullable=True),
    sa.Column('friendly_1031', sa.Boolean(), nullable=True),
    sa.Column('can_support_cohost', sa.Boolean(), nullable=True),
    sa.Column('market_type', sa.String(length=50), nullable=True),
    sa.Column('execution_type', sa.String(length=50), nullable=True),
    sa.Column('primary_strategy', sa.String(length=50), nullable=True),
    sa.Column('seasonality', sa.String(length=50), nullable=True),
    sa.Column('regulatory_clarity', sa.String(length=50), nullable=True),
    sa.Column('offer_competitiveness', sa.String(length=50), nullable=True),
    sa.Column('core_value_driver', sa.String(length=50), nullable=True),
    sa.Column('view_quality', sa.String(length=50), nullable=True),
    sa.Column('pool_type', sa.String(length=50), nullable=True),
    sa.Column('primary_guest_avatar', sa.String(length=50), nullable=True),
    sa.Column('listing_url', sa.Text(), nullable=True),
    sa.Column('loom_vid', sa.Text(), nullable=True),
    sa.Column('video_walkthrough', sa.Text(), nullable=True),
    sa.Column('survey', sa.Text(), nullable=True),
    sa.Column('note', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['market_id'], ['markets.market_keys_master.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id'),
    schema='iron_bank'
    )
    op.create_table('comp_set',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('underwriting_id', sa.Integer(), nullable=False),
    sa.Column('listing_url', sa.Text(), nullable=True),
    sa.Column('revenue', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('bedrooms', sa.Integer(), nullable=True),
    sa.Column('sleeps', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['underwriting_id'], ['iron_bank.underwritings.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    schema='iron_bank'
    )
    op.create_table('optimization_items',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('underwriting_id', sa.Integer(), nullable=False),
    sa.Column('category', sa.String(length=255), nullable=True),
    sa.Column('amount', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.ForeignKeyConstraint(['underwriting_id'], ['iron_bank.underwritings.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    schema='iron_bank'
    )
    op.create_table('underwriting_details',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('underwriting_id', sa.Integer(), nullable=False),
    sa.Column('purchase_details', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('y1_coc_incl_tax_savings', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('forecasted_revenue', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('property_details', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('setup', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('common_extras', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('cleaning_cost', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('why_this_property', sa.ARRAY(sa.Text()), nullable=True),
    sa.ForeignKeyConstraint(['underwriting_id'], ['iron_bank.underwritings.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    schema='iron_bank'
    )
    op.create_table('underwriting_taxes',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('underwriting_id', sa.Integer(), nullable=False),
    sa.Column('land_assumptions_pct', sa.Numeric(precision=6, scale=4), nullable=True),
    sa.Column('improvement_basis', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('estimated_short_life_assets', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('bonus_amount_pct', sa.Numeric(precision=6, scale=4), nullable=True),
    sa.Column('tax_rate_pct', sa.Numeric(precision=6, scale=4), nullable=True),
    sa.Column('y1_loss_from_depreciation', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('tax_savings', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.ForeignKeyConstraint(['underwriting_id'], ['iron_bank.underwritings.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    schema='iron_bank'
    )
    op.create_table('uw_operating_expenses',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('underwriting_id', sa.Integer(), nullable=False),
    sa.Column('expense_name', sa.String(length=255), nullable=True),
    sa.Column('monthly_amount', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.ForeignKeyConstraint(['underwriting_id'], ['iron_bank.underwritings.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    schema='iron_bank'
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('uw_operating_expenses', schema='iron_bank')
    op.drop_table('underwriting_taxes', schema='iron_bank')
    op.drop_table('underwriting_details', schema='iron_bank')
    op.drop_table('optimization_items', schema='iron_bank')
    op.drop_table('comp_set', schema='iron_bank')
    op.drop_table('underwritings', schema='iron_bank')
    # ### end Alembic commands ###
